import 'dart:ui';

import 'package:bar_client/core_ui/src/theme/color/app_colors.dart';
import 'package:bar_client/core_ui/src/theme/color/app_colors_theme.dart';

class LightColorsTheme extends AppColorsTheme {
  const LightColorsTheme()
      : super(
          background: AppColors.white,
          primary: AppColors.accentBlue,
          error: AppColors.dangerous,
          shadow: AppColors.dark60,
          activeIndicator: AppColors.accentBlue,
          separator: AppColors.secondaryActive,
          transparent: AppColors.transparent,
          gradient: const <Color>[
            AppColors.accentBlue80,
            AppColors.accentBlue,
          ],
          informationButtonBackground: AppColors.transparent,
          informationToastBackground: AppColors.accentBlue60,
          textColor: AppColors.dark,
          textHint: AppColors.dark60,
          textSecondary: AppColors.dark60,
          secondaryButtonBackground: AppColors.extraWhite,
          secondaryButtonActiveBackground: AppColors.dark30,
          secondaryButtonDisabledBackground: AppColors.extraWhite,
          secondaryButtonForeground: AppColors.accentBlue,
          secondaryButtonDisabledForeground: AppColors.dark40,
          outlinedButtonForeground: AppColors.accentBlue,
          outlinedButtonPressedForeground: AppColors.accentActive,
          outlinedButtonDisabledForeground: AppColors.accentBlue40,
          textButtonForeground: AppColors.accentBlue,
          textButtonPressedColor: AppColors.accentActive,
          textButtonDisabledColor: AppColors.dark30,
          textButtonOverlay: AppColors.transparent,
          filledButtonBackground: AppColors.accentBlue,
          filledButtonForeground: AppColors.white,
          filledButtonActiveBackground: AppColors.accentActive,
          filledButtonDisabledBackground: AppColors.accentBlue40,
          dialogBackground: AppColors.white,
          dialogContentText: AppColors.dark80,
          profileBackground: AppColors.extraWhite,
          profileUserIconBackground: AppColors.accentBlue10,
          profileGuestIconBackground: AppColors.dark30,
          profileSecondaryText: AppColors.dark50,
          toastForeground: AppColors.dark80,
          toastSuccessBackground: AppColors.good12,
          toastSuccessForeground: AppColors.good,
          toastErrorBackground: AppColors.dangerous12,
          toastErrorForeground: AppColors.dangerous,
          bottomBarBackground: AppColors.white,
          bottomBarShadow: AppColors.shadow,
          bottomBarTabIcon: AppColors.dark60,
          bottomBarTabIconBackground: AppColors.extraWhite,
          bottomBarTabActiveIcon: AppColors.accentBlue,
          bottomBarTabActiveIconBackground: AppColors.accentBlue10,
          onboardingTextContent: AppColors.dark80,
          filledTextFieldBackground: AppColors.accentBlue10,
          questionnaireSelected: AppColors.accentBlue,
          questionnaireNotSelected: AppColors.dark60,
          questionnaireOptionText: AppColors.dark80,
          photoBackground: AppColors.photoBackground,
          linearProgressIndicatorForeground: AppColors.accentBlue,
          linearProgressIndicatorBackground: AppColors.accentBlue10,
          homeDiagnosisButtonBackground: AppColors.accentBlue10,
          homeDiagnosisButtonPressed: AppColors.dark30,
          homeDiagnosisButtonDisabled: AppColors.extraWhite,
          homeDiagnosisButtonForeground: AppColors.dark,
          homeDiagnosisButtonPressedForeground: AppColors.dark60,
          homeDiagnosisButtonDisabledForeground: AppColors.dark40,
          diagnosisMainCardText: AppColors.white,
          diagnosisMainCardSecondary: AppColors.accentBlue10,
          diagnosisMainCardPrimary: AppColors.accentBlue,
          diagnosisCardText: AppColors.dark,
          diagnosisCardSecondaryText: AppColors.dark60,
          diagnosisCardBackground: AppColors.white,
          diagnosisCardShadow: AppColors.darkBlue,
          resultDisclaimerText: AppColors.dark80,
          diagnosisDetailsSectionTitle: AppColors.accentBlue,
          diagnosisDetailsClinicsItemTitle: AppColors.dark60,
          diagnosisDetailsTextButton: AppColors.accentBlue80,
          myDiagnosesFilterBackground: AppColors.accentBlue10,
          myDiagnosesDateFieldBorder: AppColors.dark40,
          myDiagnosesDateRangeBackground: AppColors.accentBlue10,
        );
}
