name: bar_client
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  auto_route: ^9.2.2
  retrofit: 4.1.0
  get_it: ^8.0.0
  dio: ^5.7.0
  shared_preferences: ^2.3.2
  flutter_bloc: ^8.1.6
  logger: ^2.4.0
  easy_localization: ^3.0.7
  json_annotation: ^4.9.0
  dev: ^1.0.0
  copy_with_extension: ^5.0.4
  bloc: ^8.1.4
  freezed_annotation: ^2.4.4
  mask_text_input_formatter: ^2.9.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  retrofit_generator: 8.1.2
  json_serializable: ^6.8.0
  copy_with_extension_gen: ^5.0.4
  auto_route_generator: ^9.0.0
  freezed: ^2.5.7



flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/translations/
    - assets/roboto_flex.ttf
  fonts:
    - family: Roboto Flex
      fonts:
        - asset: assets/roboto_flex.ttf